### PR TITLE
fix(core): remove transfer-encoding header in sse response

### LINKED ISSUE #6882: SseStream shouldn't set "Transfer-Encoding" to "identity"
## Bug Report

Transfer-Encoding likely should be set to "chunked", if I understand correctly. This only seems to be an issue when running behind particular reverse-proxies. [As of RFC 7230, "identity" is not a thing anymore, and we are probably off-spec for any other value. nginx only supports "chunked" anyway](https://github.com/golang/go/issues/38867).

In my particular case, NestJS application running behind Traefik, this results in the following error `net/http: HTTP/1.x transport connection broken: unsupported transfer encoding: identity`

## Possible Solution

nest/packages/core/router/sse-stream.ts
```
  pipe<T extends HeaderStream>(destination: T, options?: { end?: boolean }): T {
    if (destination.writeHead) {
      destination.writeHead(200, {
        // See https://github.com/dunglas/mercure/blob/master/hub/subscribe.go#L124-L130
        'Content-Type': 'text/event-stream',
        Connection: 'keep-alive',
        // Disable cache, even for old browsers and proxies
        'Cache-Control':
          'private, no-cache, no-store, must-revalidate, max-age=0, no-transform',
        'Transfer-Encoding': 'identity',
        Pragma: 'no-cache',
        Expire: '0',
        // NGINX support https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/#x-accel-buffering
        'X-Accel-Buffering': 'no',
      });
      destination.flushHeaders();
    }

    destination.write(':\n');
    return super.pipe(destination, options);
  }
```
Replace "identity" with "chunked"

## Environment

- Nest version: 7.6.15
- Node version: 15.14.0
- Platform:  Linux

### PR DESCRIPTION
**Pull request by ashervb**
As of RFC 7230, "identity" is no longer a valid transfer-encoding,
setting the header will cause errors.

Closes #6882

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

SSE decorated responses fail behind certain reverse proxies

Issue Number: #6882

## What is the new behavior?
SSE response will work correctly

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

File: packages/core/router/sse-stream.ts [hunk 1]
```diff
@@ -59,7 +59,6 @@ export class SseStream extends Transform {
         // Disable cache, even for old browsers and proxies
         'Cache-Control':
           'private, no-cache, no-store, must-revalidate, max-age=0, no-transform',
-        'Transfer-Encoding': 'identity',
```
Comment (jmcdo29) [inline packages/core/router/sse-stream.ts:62]: I assume this will automatically be `chunk`? If not, should we set it to that?

Comment (ashervb) [reply packages/core/router/sse-stream.ts:62]: Yes, my understanding is the [server](https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate) should set that header automatically if the content-length is unknown. Only the headers:

```
Content-Type: text/event-stream;
Cache-Control: no-cache;
X-Accel-Buffering: no;
```

[should be necessary](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)

**Review by soyuka — APPROVED** [review]

**Review by jmcdo29 — APPROVED** [review]
LGTM

**Comment by kamilmysliwiec** [comment]
LGTM
