### PR TITLE
fix(websockets): Prevent HTTP server early close in Socket.IO shutdown

### LINKED ISSUE #13910: Socket.IO Adapter Close causes premature HTTP Server close() call and blocks application shutdown
On Nest application shutdown, ``close()`` is called on the socket.io server [here](https://github.com/nestjs/nest/blob/e4b07eb06b406183e708269e0439f442a1dadb1c/packages/websockets/adapters/ws-adapter.ts#L39).

Internally *socket.io* will now disconnect all sockets handled by itself, **then calls close() on the underlying http server** [here](https://github.com/socketio/socket.io/blob/5d9a2d554440f69a0b729e276cc2578a10a173e5/packages/socket.io/lib/index.ts#L764).

This is a problem because now we are blocking until all connections on the underlying http server are closed, but before the nest application has any chance to run logic that would disconnect other long-running connections. That means that if there's a long running connection that wasn't handled by that socket.io adapter, we now block forever. 

For instance [this](https://github.com/nestjs/nest/blob/e4b07eb06b406183e708269e0439f442a1dadb1c/packages/platform-express/adapters/express-adapter.ts#L438) disconnect logic is never reached.

### PR DESCRIPTION
**Pull request by sapenlei**
fixes #13910

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #13910 

## What is the new behavior?
When ws connections and other long-running connections are handled by the same HTTP server instance, the shutdown process will not be blocked, allowing for proper termination of all connection types.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

File: packages/websockets/socket-module.ts [hunk 1]
```diff
@@ -25,8 +25,7 @@ import { WebSocketsController } from './web-sockets-controller';
 
 export class SocketModule<
   THttpServer = any,
-  TAppOptions extends
-    NestApplicationContextOptions = NestApplicationContextOptions,
+  TAppOptions extends NestApplicationOptions = NestApplicationOptions,
```
Comment (kamilmysliwiec) [inline packages/websockets/socket-module.ts:28]: This change is incorrect - SocketModule won't necessarily receive an object that implements the `NestApplicationOptions` interface

Comment (sapenlei) [reply packages/websockets/socket-module.ts]: I have changed the type from NestApplicationContextOptions back to NestApplicationOptions.

Comment (sapenlei) [reply packages/websockets/socket-module.ts]: I have changed the type from NestApplicationOptions back to NestApplicationContextOptions.

**Comment by kamilmysliwiec** [comment]
LGTM

File: packages/websockets/adapters/ws-adapter.ts [hunk 2]
```diff
@@ -35,6 +40,9 @@ export abstract class AbstractWsAdapter<
   }
 
   public async close(server: TServer) {
+    if (this._forceCloseConnections) {
+      return;
+    }
```
Comment (kamilmysliwiec) [inline packages/websockets/adapters/ws-adapter.ts:45]: @sapenlei I just realized that this method should be called no matter the `_forceCloseConnections` for non-shared WS servers. This doesn't seem to be the case atm

Comment (sapenlei) [reply packages/websockets/adapters/ws-adapter.ts:45]: Even for non-shared ws servers, their connections are destroyed and the final shutdown is closed by express

Comment (sapenlei) [reply packages/websockets/adapters/ws-adapter.ts:45]: Sorry, there's a problem. I'll fix it tomorrow

Comment (sapenlei) [reply packages/websockets/adapters/ws-adapter.ts:45]: @kamilmysliwiec   https://github.com/nestjs/nest/pull/14204
