### PR TITLE
fix(common,core): auto flush logs after `useLogger` call

### LINKED ISSUE #8733: NestFactory.createApplicationContext buffer logs does not print buffered logs to custom logger
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

NestFactory.createApplicationContext buffer logs does not print buffered logs to custom logger.

```typescript
async function bootstrap() {
  const app = await NestFactory.createApplicationContext(
    AppModule,
    {
      bufferLogs: true,
    },
  );
  app.useLogger(app.get(CustomLogger));
  app.get(CustomLogger).log('Json log');
}
bootstrap();
```

This code only logs `{"message":"Json log","logLevel":"log","appName":"MyApp"}`. It should log all of Nestjs buffered logs.

### Minimum reproduction code

https://github.com/max-abclabs/min-repro

### Steps to reproduce

1. `npm i`
2. `npm run start`

### Expected behavior

Expect the custom logger to log all buffered logs. Including the dependency injections and that the application has started successfully..

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

_No response_

### Packages versions

    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",

### Node.js version

v16.6.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

_No response_

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: closes #8733

I tested it locally with the following usages -- assuming that there was a call to `app.useLogger`:

```js
NestFactory.createApplicationContext(AppModule)
```
flushes (even tho the aren't logs buffered).

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true })
```
flushes.

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: true })
```
flushes.

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: false })
```
do not flushes.

## What is the new behavior?

When using `NestApplicationContext` app and `autoFlushLogs` is on, invoking `useLogger` method on it will flushes its logs.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

A naive attempt to address that issue without much effort. I have few concerns regarding my solution but I didn't come with anything better (nor easy to follow). Feel free to rejected it then :p

### CODE REVIEW

File: packages/core/nest-application-context.ts [hunk 1]
```diff
@@ -131,12 +133,18 @@ export class NestApplicationContext implements INestApplicationContext {
 
   public useLogger(logger: LoggerService | LogLevel[] | false) {
     Logger.overrideLogger(logger);
+
+    if (this.flushLogsOnOverride) this.flushLogs();
```
Comment (jmcdo29) [inline packages/core/nest-application-context.ts:137]: Would you mind updating the code to wrap the internals of the if in curly braces? It leads the code to be easier to follow and modify if we need to

```suggestion
    if (this.flushLogsOnOverride) {
      this.flushLogs();
    }
```

File: packages/core/nest-factory.ts [hunk 2]
```diff
@@ -142,6 +142,7 @@ export class NestFactoryStatic {
     const context = this.createNestInstance<NestApplicationContext>(
       new NestApplicationContext(container, [], root),
     );
+    if (this.autoFlushLogs) context.shouldFlushLogsOnOverride();
```
Comment (jmcdo29) [inline packages/core/nest-factory.ts:145]: Same as above

**Review by jmcdo29 — CHANGES_REQUESTED** [review]
Happy to see this added in. Left a minor comment, but the functionality itself looks fine to me

File: packages/core/nest-application-context.ts (hunk 1 above)
Comment (micalevisk) [reply packages/core/nest-application-context.ts:137]: I prefer your way tbh. I thought `npm run lint:fix` would fix that :p

File: packages/core/nest-application-context.ts [hunk 3]
```diff
@@ -35,6 +35,8 @@ export class NestApplicationContext implements INestApplicationContext {
   protected isInitialized = false;
   protected readonly injector = new Injector();
 
+  private flushLogsOnOverride = false;
+
```
Comment (kamilmysliwiec) [inline packages/core/nest-application-context.ts:39]: We can remove the blank line here

File: packages/core/nest-application-context.ts [hunk 4]
```diff
@@ -131,12 +133,20 @@ export class NestApplicationContext implements INestApplicationContext {
...
+    if (this.flushLogsOnOverride) {
+      this.flushLogs();
+    }
   }
 
   public flushLogs() {
     Logger.flush();
   }
 
+  public shouldFlushLogsOnOverride() {
```
Comment (kamilmysliwiec) [inline packages/core/nest-application-context.ts:146]: `should` word indicates here that this method should return a boolean (and shouldn't update anything itself) - it's a common convention (is/has/should)

Comment (micalevisk) [reply packages/core/nest-application-context.ts:145]: oh right.

Can we have `shouldFlushLogsOnOverride: boolean`, and `flushLogsOnOverride(): void` method instead? Otherwise I'll add `setFlushLogsOnOverride(value: boolean)`

Comment (kamilmysliwiec) [reply packages/core/nest-application-context.ts:145]: > Can we have shouldFlushLogsOnOverride: boolean, and flushLogsOnOverride(): void method instead?

Sounds great @micalevisk!

File: packages/core/nest-application-context.ts [hunk 5]
```diff
@@ -34,6 +34,7 @@ import { Module } from './injector/module';
 export class NestApplicationContext implements INestApplicationContext {
   protected isInitialized = false;
   protected readonly injector = new Injector();
+  private shouldFlushLogsOnOverride = false;
```
Comment (kamilmysliwiec) [inline packages/core/nest-application-context.ts:37]:
```suggestion

  private shouldFlushLogsOnOverride = false;
```

**Comment by kamilmysliwiec** [comment]
LGTM
