### PR TITLE
Use `isObervable` from `rxjs` instead of our own implementation. Drop few deprecated APIs from 3rd-party libs. And other minor refactorings

### LINKED ISSUE #8595: Not every object that has a `subscribe` method is an observable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Code assumes results are observables based on the presence of a subscribe method

### Minimum reproduction code
https://github.com/nestjs/nest/blob/master/packages/core/helpers/external-context-creator.ts#L332

### Steps to reproduce

In our case we returned an AsyncIterator for a graphql subscription. The returned object had a private subscribe method and nest just assumed it was an observable.

### Expected behavior

Code doesn't check for presence of a method to call a completely different method

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

_No response_

### NestJS version

_No response_

### Packages versions

- @nestjs/core 7.6.18

(current version should also be affected)

### Node.js version

_No response_

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Other

_No response_

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: closes #8595

As you can see here: https://cs.github.com/nestjs/nest?&q=isObservable there are few versions of `isObservable` on this codebase. Which are implemented as follow:

```ts
function isObservable(input): input is Observable<any> {
  return input && isFunction(input.subscribe)
}
```

I'm under assumption that all of them are supposed to return true when the input is an `Observable` object created by `rxjs` lib.

## What is the new behavior?

Using `isObservable` type guard from `rxjs` instead (introduced in `rxjs@6`)

image

which is implemented as follows [here](
https://github.com/ReactiveX/rxjs/blob/e06a472979ed29e163ad095db0125b2d82bec2f0/src/internal/util/isObservable.ts#L12):

```ts
function isObservable<T>(obj: any): obj is Observable<T> {
  return !!obj && (obj instanceof Observable || (isFunction(obj.lift) && isFunction(obj.subscribe)))
}
```

thus, I believe this should fix the linked Issue.

I've fixed the return type of `Server#transformToObservable` as well:

<details>
<summary>before</summary>

image

</details>

<details>
<summary>now</summary>

image

</details>

---

Also, I've used [`eslint-plugin-deprecation`](https://github.com/gund/eslint-plugin-deprecation) to detected and remove deprecated APIs of `rxjs` and `body-parser` and ones related with `Buffer` (nodejs). The latter only touches `.spec.ts` files.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

Do notice that, basically:

- **before:** `obj` is observable when `isFunction(obj.subscribe)`
- **now:** `obj` is observable when `isFunction(obj.subscribe) && isFunction(obj.lift)`

I'm pretty sure this means that there are no breaking changes due to how `isObservable` is being used in this codebase _but_ I could be wrong.

### CODE REVIEW

**Comment by micalevisk** [comment]
I didn't wrote missing tests for `server-grpc.ts` because I'm not familiar with gRPC.

image

Also, I didn't really understand the following

https://github.com/nestjs/nest/blob/7825c02160aae6fa4769e51eecd5530ec84a19e1/packages/microservices/server/server-grpc.ts#L257-L267

because `if (isCancelledError)` will be evaluate to true when `e !== 'canceled'`, which doesn't make sense to me.

File: packages/core/injector/injector.ts [hunk 1]
```diff
@@ -493,9 +493,8 @@ export class Injector {
   ): Promise<any> {
     let instanceWrapperRef: InstanceWrapper = null;
     const imports = moduleRef.imports || new Set<Module>();
-    const identity = (item: any) => item;
 
-    let children = [...imports.values()].filter(identity);
+    let children = [...imports.values()];
```
Comment (tonivj5) [inline packages/core/injector/injector.ts:497]:
```suggestion
    let children = imports.values();
```

**Review by jmcdo29 — APPROVED** [review]
Looks good to me

**Comment by kamilmysliwiec** [comment]
LGTM
